theme = "hugo-tania"
baseURL = 'https://jikky.dev/'
canonifyurls = true
languageCode = 'ja'
defaultContentLanguage = 'ja'
HasCJKLanguage = true
title = "ã˜ããŠã®éƒ¨å±‹"
paginate = 6
copyright = "Â© 2023 Jikky"
googleAnalytics = "G-DE6YGS2LJS"

enableGitInfo = true
[frontmatter]
  lastmod = ":git"

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "ğŸŒ™"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  siteName = "ã˜ããŠã®éƒ¨å±‹"
  siteDesc = "ã˜ã£ããƒ¼ã®ãƒ–ãƒ­ã‚°ã§ã™ã€‚AtCoderãªã©ã®ç«¶æŠ€ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚°ã®è¨˜äº‹ã‚„ã‚¢ãƒ«ã‚´ãƒªã‚ºãƒ ã®è§£èª¬ãªã©ã‚’ã¾ã¨ã‚ã¦ã„ã¾ã™ã€‚"
  author = "Jikky"

 [params.colorScheme]
   # Enable toggle colorScheme
   # Default to true
   toggle = true
   # Default colorScheme
   # Default to auto
  # default = dark

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    atcoder = ""
    3_buymeacoffee = "https://www.buymeacoffee.com/jikky"
    dev-to = ""
    discord = ""
    email = ""
    facebook = ""
    2_github = "https://github.com/Jikky1618"
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    1_twitter = "https://twitter.com/Jikky1618"
    twitch = ""
    whatsapp = ""
    4_rss = "/index.xml"
    
  
  # Comments settigns
  [params.comments]
    enabled = true
    provider = "disqus"

[menu]
[[menu.header]]
  name = "About"
  url = "/about"
[[menu.header]]
  name = "Articles"
  url = "/articles"
[[menu.header]]
  name = "Tags"
  url = "/tags"
[[menu.footer]]
  name = "Home"
  url = "../"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]