theme = "hugo-tania"
baseURL = 'https://jikky1618.github.io/Hugo-Blog/'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = "Jikky"
paginate = 6


[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "ðŸŒ™"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  siteName = "Hugo Tania is Amazing"
  siteDesc = "Hugo is Absurdly Fast!"
  author = "Hugo Tania"

  # [params.colorScheme]
  #   # Enable toggle colorScheme
  #   # Default to true
  #   toggle = true
  #   # Default colorScheme
  #   # Default to auto
  #   default = auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = ""
    facebook = ""
    github = "https://github.com/Jikky1618"
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = "https://twitter.com/Jikky1618"
    twitch = ""
    whatsapp = ""
    
  
  # Comments settigns
  [params.comments]
    enabled = true
    provider = "disqus"

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.footer]]
    name = "RSS"
    url = "/index.xml"
[[menu.footer]]
    name = "Github"
    url = "https://github.com/Jikky1618/Hugo-Blog"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]